# Generated by Django 4.2.1 on 2023-09-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zips',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
